RELEASE_NOTES.rst
bcolz/__init__.py

So that it doesn't show up when auto-completing with ipython.

privatize get_git_description

---

ANNOUNCE.rst
RELEASE_NOTES.rst
RELEASING.rst

Some obvious improvements of the relases procedure.
There are two items we should discuss in addition:
The deployment of the documentation may need to be tweaked a bit. I did set it
up to have the older docs available at:
http://bcolz.blosc.org/0.7.2/
I think this might be useful, maybe not.
Also, I don't see the value in duplicating the RELEASE_NOTES on in the wiki. In
fact I used a git clone of the wiki today and copied the release notes across
at the filesystem level.  During this I discovered, that the release notes on
the wiki had diverged(!):
https://github.com/Blosc/bcolz/wiki/Release-Notes/_compare/5d3bae0d80d8769609c4a2975f2f68a40cbfec44...ed33dff09b98ccb207a9c7e2ce68ba2d875e2dbe
If this is a good  change or not, I don't know... In any case it shows that
there is danger in …

Improve the release procedure

---

MANIFEST.in

The ``python setup.py sdist`` won't dereference symlinks so simply ship the
symlink targets too.

recursive include Blosc licences

---

bcolz/carray_ext.pyx
setup.py

See also: https://github.com/cython/cython/pull/356

remove workaround for older cython versions and pin 0.22

---

RELEASE_NOTES.rst
bcolz/carray_ext.pyx
bcolz/tests/test_carray.py

Purge was the best name I could think of, alternative suggestions welcome.

Implement ``carray.purge``

---

RELEASE_NOTES.rst
setup.py

This allows other packages to be cython compiled against the installed bcolz
package. Use case: building bquery

install carray_ext.pxd with the package

---

bcolz/carray_ext.pxd
bcolz/carray_ext.pyx
bcolz/tests/test_carray_objects.py
bcolz/utils.py

This bypasses type, dtype, and stride checking in to_ndarray.
This is unsafe behavior for general users but removes significant
overhead in the "many small writes" case typical of shuffling data.

Add safe attribute to carray

---

RELEASE_NOTES.rst
bcolz/carray_ext.pyx

Concurrent reads sometimes trigger a segfault somewhere within `blosc_decompress`. 
In principle the old bcolz code seems correct; presumably there is some issue lower down?  For now a cheap solution seems to be to hold on to the GIL.
Full trace is here:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd9c7d700 (LWP 28826)]
_int_malloc (av=0x7fffa4000020, bytes=568) at malloc.c:3489
3489	malloc.c: No such file or directory.
(gdb) bt
#0  _int_malloc (av=0x7fffa4000020, bytes=568) at malloc.c:3489
#1  0x00007ffff70907b0 in __GI___libc_malloc (bytes=568) at malloc.c:2891
#2  0x00007ffff707c44d in __fopen_internal (
filename=0x7fffa4031e90 "/home/mrocklin/data/trip3.bcolz/rate_code/data/__445.blp", 
mode=0x7fff3fc8bf80 "rb", is32=1) at iofopen.c:73
#3 …
```

Remove with nogil statement to avoid segfault

---

bcolz/ctable.py
bcolz/tests/test_ctable.py

This PR resolves #136 by modifying the ctable dtype to support multidimensional columns. Included are test cases for attempting to retrieve a total slice ([:]) from a ctable, which previously failed if the ctable had a column with >1 ndim.

Resolves #136

---

bcolz/ctable.py
bcolz/tests/test_ctable.py

As reported in #137 there is an issue with removing on-disk columns that had been created previously elsewhere:
http://nbviewer.ipython.org/gist/alimanfoo/6cc03872fe8054e63860/bcolz_ctable_delcol.ipynb
Basically, the problem is that when moving a column into the ctable, the rootdir of that carray isn't being updated.

issue regarding deletion of moved columns

---

doc/tutorial.rst

"The carray package comes with a handy object that arranges data by column (and not by row, as in NumPy’s structured arrays). This allows for much better performance for walking tabular data by column and also for adding and deleting columns."
http://bcolz.blosc.org/tutorial.html#tutorial-on-ctable-objects

Minor: docs still refer to carray name

---

RELEASE_NOTES.rst
bcolz/carray_ext.pxd
bcolz/carray_ext.pyx
bcolz/tests/test_carray.py

Hi,
this PR is a proposal for a ```chunks class``` iterator, with two tests one for in-core and the other one for  out-of-core carray.
In case this changes are on the right path, would this fill the requirements to enable this kind of syntax ```for chunk_ in ca.chunks```?
Many thanks in advance for your input,
Regards,
F. Elies

Chunks class iterator

---

bcolz/PythonHelper.h
bcolz/carray_ext.pyx
bcolz/definitions.pxd

IIRC before Python version 2.6 we still needed the compat layer, now we can
just go ahead and call everything PyBytes_* as it is suppoed to be in Python
3.x.

remove compat layer and rename

---

bcolz/ctable.py

```python
print bcolz.__version__
N = 100*100
ct = bcolz.fromiter(((i,i*i) for i in xrange(N)), dtype="i4,f8", count=N, rootdir='test')
new_col = np.linspace(0, 1, 100*100)
ct.addcol(new_col)
```
```
0.8.1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-6c6f9912fdbb> in <module>()
1 print bcolz.__version__
2 N = 100*100
----> 3 ct = bcolz.fromiter(((i,i*i) for i in xrange(N)), dtype="i4,f8", count=N, rootdir='test')
4 new_col = np.linspace(0, 1, 100*100)
5 ct.addcol(new_col)
/opt/miniconda/lib/python2.7/site-packages/bcolz/toplevel.pyc in fromiter(iterable, dtype, count, **kwargs)
193         obj = bcolz.ctable(np.array([], dtype=dtype),
194 …
```

Creating ctable with rootdir kwarg causes ValueError: You cannot pass a `columns` param in 'a'ppend mode

---

bcolz/ctable.py
bcolz/tests/test_ctable.py

It wasn't possible to initialize a ctable with the auto_flush keyword at all.
Problem is: the **kwargs are being sent through to any new carrays and these
don't support this keyword argument.
There are multiple approaches to solving this problem:
a) Pop the auto_flush keyword from the **kwargs if it exists (current solution)
b) Implement auto_flush in the carray
c) Remove the auto_flush keyword entirely in favour of with statement.
(Although this might not be enough to support all use-cases.)

Fix using the auto_flush keyword in the ctable constructor

---

bcolz/carray_ext.pyx
bcolz/definitions.pxd

avoid redundant memory copy in chunk.getudata

---

bcolz/carray_ext.pyx

In some rare cases using the standard mod operator in cython was causing the leftover value to
be incorrectly set to a non-zero value. This was causing segfaults in bdot (and probably bquery), from attempts to write outside the bounds of correctly sized result arrays in cython.
This example reproduced the bug in my tests.
```python
rows = 2 ** 21
columns = 200
matrix = np.random.random_integers(0, 120, size=(rows, columns))
chunk_len = 2 ** 2
bcarray = bdot.carray(matrix, chunklen=chunk_len, cparams=bdot.cparams(clevel=2))
```
See the 'Abstract' section of this document for details on the differences between standard mod and `cython.cmod`: [Enhancements Division](https://github.com/cython/cython/wiki/enhancements-division)

fix bug for incorrect leftover value

---

RELEASE_NOTES.rst
bcolz/tests/test_carray.py
bcolz/utils.py

Continuation of #217. The fix there only works for transposed arrays, but it still fails to fix errors with, for example, pandas dataframes:
```python
import pandas as pd
import bcolz
df = pd.DataFrame(data={
'a': np.arange(3),
'b': np.arange(3)[::-1]
})
print(df)
a  b
0  0  2
1  1  1
2  2  0
print(bcolz.carray(df))
[[0 1]
[2 2]
[1 0]]
```
This is the same example we had in #217, run with latest master (e260ca71bc) installed on latest anaconda. I'm working in a fix for this that will do the right thing (the first commit here is a step, but breaks other conversions).

do not assume that `np.array` does the right thing

---

RELEASE_NOTES.rst
bcolz/ctable.py
bcolz/tests/test_ctable.py

Added a new test for this enhancement.

added support for appending np.void in ctables. fixes ticket #229

---

bcolz/ctable.py

Using all() instead of comparing a list of objects to a list of types allows more flexible checks and stops as soon as False is found.

using all() to check types for a list of objects

---

bcolz/ctable.py
bcolz/tests/test_ctable.py

When directly invoking the `ctable` constructor with a rootdir and and mode = 'r', the following error gets raised:
```
In [1]: from bcolz import ctable
In [2]: ctable(rootdir='/not/real/', mode='r')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-d959ad9bc242> in <module>()
----> 1 ctable(rootdir='/not/real/', mode='r')
/home/ssanderson/clones/bcolz/bcolz/ctable.py in __init__(self, columns, names, **kwargs)
219         _new = False
220         if self.mode in ('r', 'a'):
--> 221             self.open_ctable()
222         elif columns is not None:
223             self.create_ctable(columns, names, **kwargs)
/home/ssanderson/clones/bcolz/bcolz/ctable.py in …
```

Provide a better error when opening a ctable for read with a nonexistent rootdir.

---

asv.conf.json

@FrancescAlted this should fix https://github.com/Blosc/bcolz/pull/253#issuecomment-145458834
Could you please give it a try

fix: asv gets confused with `bcolz` project name

---

RELEASE_NOTES.rst
bcolz/ctable.py
bcolz/py2help.py
bcolz/tests/test_ctable.py
bcolz/tests/test_queries.py

This fixes up string-type handling in a few places.  Bcolz has a py2helper module for aiding Python 2/3 compatibility, but wasn't using it in several places.  This results in problems when using bcolz with Python 2 for various tasks (e.g., selecting multiple columns whose names are given as unicode strings, see also #272 ).
I wrote a couple tests to test unicode handling, and everything is passing on Py2, but I'm not set up right now to test bcolz on Python 3, so hopefully someone else (like maybe the helpful Mr. Travis) can check that.

Py2strings

---

RELEASE_NOTES.rst
setup.py

Use a lazy cmdclass object to defer accesses to `numpy` and `Cython`
until after those modules have been installed by `setuptools` via
`setup_requires`.
Without this, the fact that we're supplying numpy and Cython in
`setup_requires` is meaningless, because we access numpy at module
scope, well before we're able to tell `setuptools` that we require
numpy.
I built this because I'm trying to remove several hacks and workarounds in the [zipline setup.py](https://github.com/quantopian/zipline/pull/867) to allow users to install zipline without needing to first install numpy.  The linked PR achieves that goal, but we fail installing `bcolz` because it tries to import numpy at module scope.

BLD: Defer numpy/Cython operations in setup.py.

---

RELEASE_NOTES.rst
bcolz/carray_ext.pyx

As discussed in #282, these changes remove some overheads when slicing a carray without a step, as is common when computing some result chunk-by-chunk. All tests pass. Profiling data showing the improvement is here: http://nbviewer.ipython.org/gist/alimanfoo/88a937ef0953f4a3c5d1/bcolz_profile_getitem.ipynb

optimisations for carray.__getitem__ with slice and no step

---

bcolz/carray_ext.pyx

Currently there is overhead within ``carray.__setitem__`` when replacing one or more entire chunks. Overhead arises because the loop is over all chunks, checking for overlap with clip_chunks, and because the contents of chunks with data to be replaced are always read first, even if the entire chunk's data is going to be replaced. Modifying the for loop and checking to see if an entire chunk can be replaced removes this overhead. This can cut the time for ``__setitem__`` calls in half. All tests pass. Profiling data here: http://nbviewer.ipython.org/gist/alimanfoo/88a937ef0953f4a3c5d1/bcolz_profile_setitem.ipynb

Optimise carray.__setitem__ for slice with no step

---

bcolz/ctable.py
bcolz/tests/test_ctable.py

Hello,
In `ctable.todataframe`, when you specify `columns` and `orient='columns'`, pandas checks that the length of the generator is less than the number of columns. However, generators don't have lengths so it crashes. This just limits the generator the requested columns to get around that.

BUG: todataframe with columns specified

---

bcolz/ctable.py

See issue Blosc/bcolz#351 for description of problem fixed by this
commit.

Allow unsigned integer arrays when indexing ctables

---

cpuinfo.py

otherwise installation aborts with the exception "py-cpuinfo currently only works on X86 and some ARM CPUs."

Make cpuinfo work on Tegra Jetson TX1

---

bcolz/chunked_eval.py
bcolz/tests/test_queries.py

The __eval_blocks() function in chunked_eval.py mishandles np.datetime64 objects since they for some reason have the __getitem__ attribute. This fix should allow users to use ctable.fetchwhere() functions off of datetime queries.

Handling of np.datetime64 and other scalar objects that have __getitem__ attribute in _eval_blocks()

---

docs/tutorial_ctable.ipynb

Changes made in this PR:
`xrange` is no longer existed in Python 3, to make PY2 & PY3 compatible for running `docs/tutorial_ctable.ipynb`, I made an alias for `xrange` function in PY2:
```python
import sys
if sys.version_info[0] == 2:
range = xrange
```

Fix compatibility issue of xrange func in ctable tutorial notebook.

---

docs/tutorial_carray_memory_profile.ipynb

This PR fixed following thing:
1. PY2 & PY3 Compatibility: `print d` -> `print(d)`
2. `pd.options.display.mpl_style` is removed from pandas API. Remove this line will just use the default style.
3. In most recent pandas version, `pd.DataFrame({'MiB': arange_results.values()}, index=arange_results.keys())` create a DataFrame contains 1 column with 3 identical tuple as it's values. So I also update this API usage.

Fix outdated package API usages in Doc tutorial Notebook

---

bcolz/ctable.py
bench/pandas-fromdataframe-strings.py
bench/pandas-fromdataframe.py
bench/pandas-todataframe.py

Pandas has deprecated DataFrame.from_items. Replace with recommended approach
of DataFrame.from_dict(OrderedDict(...)).

Fix deprecation of DataFrame.from_items
