Blosc/bcolz

RELEASE_NOTES.rst
bcolz/carray_ext.pyx
bcolz/tests/test_carray.py

So one can see at a glance what one can do with this array.

Add the io 'mode' to the 'repr' for 'carray's

---

README.rst

adding badged to the README

---

makefile

Nothing to see here, please move along.

adding makefile

---

RELEASE_NOTES.rst
bcolz/carray_ext.pyx
bcolz/tests/test_carray.py
bcolz/tests/test_ctable.py
bcolz/utils.py

Some additional fixes and cleanups.

Rebased version of #193

---

bcolz/carray_ext.pyx

It became available with #153 here is how to use it.

start making use of the chunks iterator

---

bcolz/carray_ext.pxd
bcolz/carray_ext.pyx

factor out generating the chunk file name

---

README.rst

Include this in the README.rst

appveyor badge

---

bcolz/carray_ext.pyx

Related to https://github.com/Blosc/bcolz/issues/22
I started marking some methods with a single underscore, would you prefer double underscore for that?

Carray private methods

---

bcolz/carray_ext.pyx
bcolz/tests/test_carray.py

Context manager support for disk-based carrays

with statement

---

README.rst

can't connect to https://blosc.org, would http://blosc.org forwarding be ok?

blosc http

---

setup.py

automatically install cython and numpy with setuptools
* easier pip install
* enables use of airspeed velocity for benchmarking

leverage setuptools for smoother install

---

.travis.yml

Installs numpy pandas cython for every environment, mock and unittest2 depending on environment.

Travis using conda

---

bcolz/carray_ext.pyx
bcolz/tests/test_carray.py

PR exposing issue https://github.com/Blosc/bcolz/issues/61

TestCase sudden ndarray type

---

bcolz/ctable.py
bcolz/tests/test_ctable.py

I had some spare time, this PR should fix https://github.com/Blosc/bcolz/issues/179 ( test and bugfix  already proposed by @brentp in the previous link)

TestCase + fix for #179

---

RELEASE_NOTES.rst
bcolz/tests/test_ctable.py

np 1.10 compat: replace "f16" dtype with np.longdouble

---

pavement.py

- https://github.com/Blosc/bcolz/issues/118
- https://github.com/Blosc/bcolz/issues/275

Compare package installed versions with desirable version via distutils.version.LooseVersion

---

setup.py

correct Numpy setup code.

---

.travis.yml
bcolz/chunked_eval.py
bcolz/tests/test_carray.py

[WIP] PR about chunking over (n, 1) arrays

---

bcolz/ctable.py

Don't use named tuple bc > 255 columns

---

bcolz/ctable.py

changed error message in validate_names()

---

bcolz/toplevel.py
docs/install.rst

This PR has a couple of minor edits to the docs:
* Add install instructions for conda-forge
* Add zstd to list of available compressors (resolves #331)

Docs 20170209
